--- #YAML:1.0
name:               WWW-Mechanize-Firefox
version:            0.31
abstract:           use Firefox as if it were WWW::Mechanize
author:
    - Max Maischein <corion@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTML::Selector::XPath:  0
    HTTP::Response:       0
    MIME::Base64:         0
    MozRepl::RemoteObject:  0.11
    parent:               0
    perl:                 5.006
    Scalar::Util:         1.14
    Shell::Command:       0
    Task::Weaken:         0
    URI:                  0
    WWW::Mechanize:       0
    WWW::Mechanize::Link:  0
resources:
    repository:  http://github.com/Corion/www-mechanize-firefox
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
